# frozen_string_literal: true

require_relative 'mailersend/client'
require_relative 'mailersend/version'
require_relative 'mailersend/activity/activity'
require_relative 'mailersend/analytics/analytics'
require_relative 'mailersend/bulk_email/bulk_email'
require_relative 'mailersend/domains/domains'
require_relative 'mailersend/email/email'
require_relative 'mailersend/inbound_routing/inbound_routing'
require_relative 'mailersend/messages/messages'
require_relative 'mailersend/recipients/recipients'
require_relative 'mailersend/scheduled_messages/scheduled_messages'
require_relative 'mailersend/suppressions/suppressions'
require_relative 'mailersend/templates/templates'
require_relative 'mailersend/tokens/tokens'
require_relative 'mailersend/webhooks/webhooks'
