name: Ruby

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.0

    - name: Install Bundler
      run: gem install bundler -v 2.4.22

    - name: Install dependencies
      run: bundle _2.4.22_ install

    - name: Run the default task
      run: bundle exec rake
